/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;


import utilitaire.CollectionClient;
import utilitaire.CollectionProspect;
import metiers.Client;
import metiers.Prospect;
import metiers.Societe;

/**
 *
 * @author Alexandre Colomar
 */
public class Accueil extends javax.swing.JFrame {

    Societe societe;
    String choix;     
    private boolean ajouterFlag = false;
    private boolean supprimerFlag = false;
    private boolean modifierFlag = false;
    private boolean afficherFlag = false;
    private boolean clientFlag = true;
    private boolean prospectFlag = false;
       

    private void instanceFormulaire(){
            Formulaire formulaire = new Formulaire(choix, societe);
            formulaire.setVisible(true);
            this.dispose();                
            }   
        
    public boolean isAjouterFlag() {
        return ajouterFlag;
    }
    public void setAjouterFlag(boolean ajouterFlag) {
        this.ajouterFlag = ajouterFlag;
    }
    public boolean isSupprimerFlag() {
        return supprimerFlag;
    }
    public void setSupprimerFlag(boolean supprimerFlag) {
        this.supprimerFlag = supprimerFlag;
    }
    public boolean isModifierFlag() {
        return modifierFlag;
    }
    public void setModifierFlag(boolean modifierFlag) {
        this.modifierFlag = modifierFlag;
    }
    public boolean isAfficherFlag() {
        return afficherFlag;
    }
    public void setAfficherFlag(boolean afficherFlag) {
        this.afficherFlag = afficherFlag;
    }
    public boolean isClientFlag() {
        return clientFlag;
    }    
    public void setClientFlag(boolean clientFlag) {
        this.clientFlag = clientFlag;
    }
    public boolean isProspectFlag() {
        return prospectFlag;
    }
    public void setProspectFlag(boolean prospectFlag) {
        this.prospectFlag = prospectFlag;
    }
       
    /**
     * Creer nouveau formulaire d'accueil
     */
    public Accueil() {     
        initComponents();
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        pnlChoixOperation = new javax.swing.JPanel();
        btnAjouter = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnAfficher = new javax.swing.JButton();
        btnValider2 = new javax.swing.JButton();
        btnRetourAccueil = new javax.swing.JButton();
        boxRaisonSociale = new javax.swing.JComboBox<>();
        pnlAccueil = new javax.swing.JPanel();
        boxSociete = new javax.swing.JComboBox<>();
        btnValider1 = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 300));

        titre.setText("GESTIONNAIRE DE CLIENT");

        pnlChoixOperation.setVisible(false);

        btnAjouter.setText("ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnSupprimer.setText("supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnModifier.setText("modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnAfficher.setText("afficher");
        btnAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherActionPerformed(evt);
            }
        });

        btnValider2.setText("valider");
        btnValider2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValider2ActionPerformed(evt);
            }
        });

        btnRetourAccueil.setText("accueil");
        btnRetourAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourAccueilActionPerformed(evt);
            }
        });

        boxRaisonSociale.setVisible(false);
        boxRaisonSociale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRaisonSocialeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChoixOperationLayout = new javax.swing.GroupLayout(pnlChoixOperation);
        pnlChoixOperation.setLayout(pnlChoixOperationLayout);
        pnlChoixOperationLayout.setHorizontalGroup(
            pnlChoixOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChoixOperationLayout.createSequentialGroup()
                .addGroup(pnlChoixOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChoixOperationLayout.createSequentialGroup()
                        .addComponent(btnAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSupprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAfficher))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChoixOperationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRetourAccueil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnValider2)))
                .addContainerGap())
            .addGroup(pnlChoixOperationLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(boxRaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlChoixOperationLayout.setVerticalGroup(
            pnlChoixOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChoixOperationLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlChoixOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnSupprimer)
                    .addComponent(btnModifier)
                    .addComponent(btnAfficher))
                .addGap(18, 18, 18)
                .addComponent(boxRaisonSociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlChoixOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValider2)
                    .addComponent(btnRetourAccueil)))
        );

        boxSociete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "client", "prospect" }));
        boxSociete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxSocieteActionPerformed(evt);
            }
        });

        btnValider1.setText("valider");
        btnValider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAccueilLayout = new javax.swing.GroupLayout(pnlAccueil);
        pnlAccueil.setLayout(pnlAccueilLayout);
        pnlAccueilLayout.setHorizontalGroup(
            pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccueilLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(boxSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnValider1)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlAccueilLayout.setVerticalGroup(
            pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccueilLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValider1)
                    .addComponent(boxSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        btnQuit.setText("quitter");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlChoixOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(titre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnQuit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuit))
                .addGap(26, 26, 26)
                .addComponent(pnlAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlChoixOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxRaisonSocialeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRaisonSocialeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRaisonSocialeActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
   
    boxRaisonSociale.setVisible(true);
    supprimerFlag = true;
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnValider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValider1ActionPerformed
        pnlChoixOperation.setVisible(true);
        
//POUR chaque objet client issu de la collectionClient, ajouter la raison sociale de ce client  a la boxRaisonSociale
            
        if(boxSociete.getSelectedItem().equals("client")){
            
            for(Client client: CollectionClient.getListeClient()){
            boxRaisonSociale.addItem(client.getRaisonSociale());
            }
        } else {
            for(Prospect prospect: CollectionProspect.getListeProspect()){
            boxRaisonSociale.addItem(prospect.getRaisonSociale());
        }
      }  
        
    }//GEN-LAST:event_btnValider1ActionPerformed

    private void btnRetourAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourAccueilActionPerformed
     pnlChoixOperation.setVisible(false); 
     ajouterFlag = false;
     supprimerFlag = false;
     modifierFlag = false;
     afficherFlag = false;
     boxRaisonSociale.setVisible(false); 
     Accueil accueil = new Accueil();
     accueil.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnRetourAccueilActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        boxRaisonSociale.setVisible(true); 
        modifierFlag = true;
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnValider2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValider2ActionPerformed

        

        
        if(supprimerFlag ){
            
            if(boxSociete.getSelectedItem().equals("client") ){   
            choix = "clientSupprimer";
           societe = CollectionClient.getListeClient().get(boxRaisonSociale.getSelectedIndex());
            } else {
                 choix = "prospectSupprimer"; 
                 societe = CollectionProspect.getListeProspect().get(boxRaisonSociale.getSelectedIndex());
            }

            Formulaire formulaire = new Formulaire(choix, societe);
            formulaire.setVisible(true);
            this.dispose();   
        } else {
            if(modifierFlag){
                
                            if(boxSociete.getSelectedItem().equals("client") ){   
            choix = "clientModifier";
           societe = CollectionClient.getListeClient().get(boxRaisonSociale.getSelectedIndex());
            } else {
                 choix = "prospectModifier"; 
                 societe = CollectionProspect.getListeProspect().get(boxRaisonSociale.getSelectedIndex());
            }
            instanceFormulaire();
                
            }
        }

    }//GEN-LAST:event_btnValider2ActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        ajouterFlag = true;

        if(boxSociete.getSelectedItem().equals("client") && ajouterFlag == true){   
           choix = "clientAjouter";
           societe = null;
       } else {
            choix = "prospectAjouter"; 
            societe = null;
       }        
            instanceFormulaire();    
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherActionPerformed
        afficherFlag = true;
              
        
        if(boxSociete.getSelectedItem().equals("client") && afficherFlag == true){
    
           choix = "client";

 
       } else {
            choix = "prospect";
            
       }
 
        Liste liste = new Liste(choix);
        liste.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAfficherActionPerformed

    private void boxSocieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxSocieteActionPerformed
      
    }//GEN-LAST:event_boxSocieteActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
                
            }
        });
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxRaisonSociale;
    private javax.swing.JComboBox<String> boxSociete;
    private javax.swing.JButton btnAfficher;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRetourAccueil;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnValider1;
    private javax.swing.JButton btnValider2;
    private javax.swing.JPanel pnlAccueil;
    private javax.swing.JPanel pnlChoixOperation;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
