/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframe;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import jframe.Accueil;
import metiers.Client;
import metiers.Prospect;
import utilitaire.CollectionClient;
import utilitaire.CollectionProspect;
/**
 *
 * @author CDA03-02
 */
public class Liste extends javax.swing.JFrame {

    String choix;
    static DefaultTableModel modelClient;
   
    /**
     * Creates new form Liste
     */
    
    public  Liste() {
        initComponents();
  
    }
    
    public Liste(String choix) {

        initComponents();

           
        this.choix = choix;
 

       if(choix.equals("client")){
           
            String[] entete ={"identifiant","raison sociale","adresse","telephone","mail","chiffre d'affaire", "nombre d'employé","commentaire"};            
            modelClient = new DefaultTableModel(new Object [][]{}, entete);
            titreListe.setText("Liste Client");
            Collections.sort(CollectionClient.getListeClient(), CollectionClient.triListe);
           
           for(Client client: CollectionClient.getListeClient()){
               modelClient.addRow(new Object[]{
                   client.getIdentifiant(),
                   client.getRaisonSociale(),
                   client.getNumeroRue() + " " + client.getNomRue() + " " + client.getCodePostal() + " " + client.getVille(),
                   client.getTelephone(),
                   client.getMail(),
                   client.getChiffreAffaire(),
                   client.getNbEmploye(),
                   client.getCommentaire()
                       
               });
           }
           tableau.setModel(modelClient);
           
           
       } else {
           if(choix.equals("prospect")){
               
            String[] entete ={"identifiant","raison sociale","adresse","telephone","mail","date de prospection", "intêret", "commentaire"};            
            modelClient = new DefaultTableModel(new Object [][]{}, entete);
            titreListe.setText("Liste Prospect");
            Collections.sort(CollectionProspect.getListeProspect(), CollectionClient.triListe);
           
           for(Prospect prospect: CollectionProspect.getListeProspect()){
               modelClient.addRow(new Object[]{
                   prospect.getIdentifiant(),
                   prospect.getRaisonSociale(),
                   prospect.getNumeroRue() + " " + prospect.getNomRue() + " " + prospect.getCodePostal() + " " + prospect.getVille(),
                   prospect.getTelephone(),
                   prospect.getMail(),
                   prospect.getDateProspection(),
                   prospect.getProspectInterest(),
                   prospect.getCommentaire()
      
               });
           }    
           tableau.setModel(modelClient);   
               
           }
           
       }
       
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        titreListe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        retourAccueil = new javax.swing.JButton();
        btnQuitListe = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));

        titreListe.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        titreListe.setText("Liste");

        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableau.setPreferredSize(new java.awt.Dimension(800, 600));
        jScrollPane1.setViewportView(tableau);

        retourAccueil.setText("accueil");
        retourAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourAccueilActionPerformed(evt);
            }
        });

        btnQuitListe.setText("quitter");
        btnQuitListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitListeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnQuitListe)
                .addGap(18, 18, 18)
                .addComponent(retourAccueil)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(titreListe, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titreListe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retourAccueil)
                    .addComponent(btnQuitListe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourAccueilActionPerformed

     Accueil accueil = new Accueil();
     accueil.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_retourAccueilActionPerformed

    private void btnQuitListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitListeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitListeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Liste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuitListe;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retourAccueil;
    private javax.swing.JTable tableau;
    private javax.swing.JLabel titreListe;
    // End of variables declaration//GEN-END:variables
}
